#!/bin/bash

subl="subl" # command line sublime application

open_sublime_scope="0"
open_sublime_long="open-sublime"
open_sublime_short="o"

flags=("open_sublime")

source "bashargs.sh"

if [[ ${#arguments[@]} -gt 1 ]]; then
  name="${arguments[0]}"
  echo "Warning: passed multiple names, using the first (${name})"
elif [[ ${#arguments[@]} -eq 1 ]]; then
  name="${arguments[0]}"
else
  name="${PWD##*/}"
  read -p "Do you want to use ${name} as the project name? "
  if [[ ! $REPLY =~ ^[Yy]([Ee][Ss])?$ ]]; then
    echo "Not using the suggested name, aborting"; exit 1
  fi
fi

name_path="${name}.sublime-project"

if [[ -e "${name_path}" ]]; then
  if [ ${open_sublime} ]; then
    ${subl} --project ${name_path}; exit 0
  else
    echo "The file "${name_path}" already exists, aborting"; exit 1
  fi
fi

echo "Writing ${name_path}"

cat >"${name_path}" <<EOF
{
  "folders": [
    {
      "path": ".",
      "file_exclude_patterns": [],
      "folder_exclude_patterns": []
    }
  ],
  "build_systems": []
}
EOF

if [ ${open_sublime} ]; then 
    ${subl} ${name_path} --project ${name_path}; exit 0
fi
